spring.datasource.url=jdbc:postgresql://patient-db:5432/patient_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always

spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.producer.bootstrap-servers=kafka:9092

# Elasticsearch
spring.elasticsearch.uris=http://elasticsearch:9200

# Swagger/OpenAPI Configuration
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.use-fqn=true

