spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=analytics-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer

# Swagger/OpenAPI Configuration
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.api-docs.path=/v3/api-docs
springdoc.use-fqn=true
springdoc.info.title=Analytics Service API
springdoc.info.description=API for analytics and events
springdoc.info.version=1.0.0
springdoc.api-docs.server-url=http://localhost:4004
